name: "Todos"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO-2-GH-Issue"
        uses: "jamminroot/todo-2-gh-issue@master"
        with:
          TOKEN: "1e867036d635d6a59e5763c82e51ea2206d4c77b"
          TODO_PATTERN: "(?<=\\/\\/ ?TODO[ :]).+"
          TRIM: ",: \""
          TIMEOUT: 1000
          LINES_BEFORE: 2
          LINES_AFTER: 5
          LABELS_PATTERN: "(?<=\\[).+?(?=\\])"
          LABELS_REPLACE_PATTERN: "\\[(.+?)\\]"
          IGNORED_LINES_LENGTH: 255
        id: "todo"
